export const organisations = [
  {
    name: 'Paws & Meals',
    description: 'Provides food and nutrition for shelter dogs across the country.',
    image: 'orgs/paws-meals.jpg',
    stripePriceId: 'price_org_dogfood',
    suggestedAmount: 20.00,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Joyful Tails Foundation',
    description: 'Delivers toys and enrichment to animals in foster care.',
    image: 'orgs/joyful-tails.jpg',
    stripePriceId: 'price_org_toys',
    suggestedAmount: 10.00,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Feline Dreams',
    description: 'Provides safe beds and comfort for rescued cats.',
    image: 'orgs/feline-dreams.jpg',
    stripePriceId: 'price_org_catbed',
    suggestedAmount: 15.00,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'AquaAid Initiative',
    description: 'Creates safe habitats for rescued aquatic animals.',
    image: 'orgs/aquaaid.jpg',
    stripePriceId: 'price_org_aquarium',
    suggestedAmount: 25.00,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Feathered Friends Trust',
    description: 'Supports rescued birds with housing, food, and enrichment.',
    image: 'orgs/feathered-friends.jpg',
    stripePriceId: 'price_org_birdcare',
    suggestedAmount: 18.00,
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Reptile Rescue Network',
    description: 'Ensures proper habitats, food, and heat for reptiles in need.',
    image: 'orgs/reptile-rescue.jpg',
    stripePriceId: 'price_org_reptile',
    suggestedAmount: 22.00,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Whisker Wellness',
    description: 'Focuses on grooming and hygiene care for rescue cats.',
    image: 'orgs/whisker-wellness.jpg',
    stripePriceId: 'price_org_grooming',
    suggestedAmount: 12.00,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Critter Comfort',
    description: 'Provides bedding and shelters for small animals like hamsters and guinea pigs.',
    image: 'orgs/critter-comfort.jpg',
    stripePriceId: 'price_org_bedding',
    suggestedAmount: 8.00,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Wagging Walks',
    description: 'Equips shelters with leashes and walking gear for dogs.',
    image: 'orgs/wagging-walks.jpg',
    stripePriceId: 'price_org_walks',
    suggestedAmount: 14.00,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Treats & Tails',
    description: 'Supplies healthy treats for animals in care to boost joy and training.',
    image: 'orgs/treats-tails.jpg',
    stripePriceId: 'price_org_treats',
    suggestedAmount: 10.00,
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]